app:
  date_overlapping: true
logger:
  level : debug # info / debug / warning / error
storage:
  type: sql
  dsn: "postgres://postgres:postgres@postgres:5432/calendar"
http:
  host: 0.0.0.0
  port: 80
grpc:
  host: 192.168.2.64
  port: 81